version: '2'
services:
    web:
        build: ./web
        ports:
            - "127.0.0.1:9500:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
